import { defineStore } from "pinia";
import { ref, computed } from "vue";

export const useRoleStore = defineStore("role", () => {
  const roleNow = ref("knight"); // default role

  const roles = ref({
    prince: {
      basic: {
        lv: 1,
        exp: "0.00%",
        hp: 34,
        mp: 2,
        ac: 10,
        mr: 10,
        str: 18,
        dex: 10,
        con: 10,
        int: 11,
        wis: 10,
        cha: 18,
      },

      equips: [
        {
          id: 0,
          name: "大馬士革刀",
          src: `/src/assets/prince/equips/equip_weapon.png`,
          category: "weapon",
          attack: {
            small: 10,
            large: 11,
          },
          grip: "單手武器",
          value: 0,
          safetyValue: 6,
          material: "鐵",
          weight: 45,
          occupation: "[妖精][王族][騎士]",
          feature: "不會損壞",
        },
        {
          id: 1,
          name: "抗魔法頭盔",
          src: "/src/assets/prince/equips/equip_helmet.png",
          category: "armor helmet",
          armor: 2,
          value: 0,
          safetyValue: 4,
          material: "鐵",
          weight: 35,
          occupation: "[所有職業]",
          feature: "魔法防禦額外點數 +4",
        },
        {
          id: 2,
          name: "妖魔戰士護身符",
          src: "/src/assets/prince/equips/equip_amulet.png",
          category: "jewelry amulet",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "寶石",
          weight: 5,
          occupation: "[所有職業]",
          feature: "體力上限+20",
        },
        {
          id: 3,
          name: "T恤",
          src: "/src/assets/prince/equips/equip_shirt.png",
          category: "armor shirt",

          armor: 0,
          value: 0,
          safetyValue: 4,
          material: "布",
          weight: 5,
          occupation: "[所有職業]",
          feature: null,
        },
        {
          id: 4,
          name: "精靈鏈甲",
          src: "/src/assets/prince/equips/equip_BodyArmor.png",
          category: "armor bodyArmor",
          armor: 5,
          value: 0,
          safetyValue: 6,
          material: "米索莉",
          weight: 150,
          occupation: "[所有職業]",
          feature: null,
        },
        {
          id: 5,
          name: "保護者斗篷",
          src: "/src/assets/prince/equips/equip_cloak.png",
          category: "armor cloak",
          armor: 3,
          value: 0,
          safetyValue: 4,
          material: "布",
          weight: 10,
          occupation: "[所有職業]",
          feature: null,
        },
        {
          id: 6,
          name: "瞬間移動控制戒指",
          src: "/src/assets/prince/equips/equip_left-ring.png",
          category: "jewelry left-ring",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "金",
          weight: 3,
          occupation: "[所有職業]",
          feature: "使用傳送術或傳送道具時，可以指定傳送到曾經記憶過的地點",
        },
        {
          id: 7,
          name: "歐吉皮帶",
          src: "/src/assets/prince/equips/equip_belt.png",
          category: "jewelry belt",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "皮",
          weight: 50,
          occupation: "[所有職業]",
          feature: "增加負重+1000",
        },
        {
          id: 8,
          name: "反射之盾",
          src: "/src/assets/prince/equips/equip_shield.png",
          category: "armor shield",
          armor: 2,
          value: 0,
          safetyValue: 4,
          material: "銀",
          weight: 50,
          occupation: "[妖精][王族][騎士]",
          feature: null,
        },
        {
          id: 9,
          name: "力量手套",
          src: "/src/assets/prince/equips/equip_gloves.png",
          category: "armor gloves",
          armor: 0,
          value: 0,
          safetyValue: 4,
          material: "皮",
          weight: 18,
          occupation: "[所有職業]",
          feature: "力量 +2",
        },
        {
          id: 10,
          name: "形體控制戒指",
          src: "/src/assets/prince/equips/equip_right-ring.png",
          category: "jewelry right-ring",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "金",
          weight: 3,
          occupation: "[所有職業]",
          feature: "使用變身術或變身道具時，可以指定要變身的怪物",
        },
        {
          id: 11,
          name: "鋼鐵長靴",
          src: "/src/assets/prince/equips/equip_boots.png",
          category: "armor boots",
          armor: 3,
          value: 0,
          safetyValue: 4,
          material: "鐵",
          weight: 50,
          occupation: "[所有職業]",
          feature: null,
        },
      ],
    },
    knight: {
      basic: {
        lv: 1,
        exp: "0.00%",
        hp: 86,
        mp: 1,
        ac: 10,
        mr: 0,
        str: 22,
        dex: 12,
        con: 14,
        int: 9,
        wis: 8,
        cha: 12,
      },

      equips: [
        {
          id: 0,
          name: "瑟魯基之劍",
          src: `/src/assets/knight/equips/equip_weapon.png`,
          category: "weapon",
          attack: {
            small: 16,
            large: 10,
          },
          grip: "單手武器",
          value: 0,
          safetyValue: 6,
          material: "金屬",
          weight: 120,
          occupation: "[騎士]",
          feature: "近距離命中+2",
        },
        {
          id: 1,
          name: "騎士面甲",
          src: "/src/assets/knight/equips/equip_helmet.png",
          category: "armor helmet",
          armor: 3,
          value: 0,
          safetyValue: 4,
          material: "鐵",
          weight: 40,
          occupation: "[騎士]",
          feature: null,
        },
        {
          id: 2,
          name: "妖魔戰士護身符",
          src: "/src/assets/knight/equips/equip_amulet.png",
          category: "jewelry amulet",
          toDisplay: {
            armor: 0,
            value: 0,
            safetyValue: 0,
            material: "寶石",
            weight: 5,
            occupation: "[所有職業]",
            feature: "體力上限+20",
          },
        },
        {
          id: 3,
          name: "T恤",
          src: "/src/assets/knight/equips/equip_shirt.png",
          category: "armor shirt",
          armor: 0,
          value: 0,
          safetyValue: 4,
          material: "布",
          weight: 5,
          occupation: "[所有職業]",
          feature: null,
        },
        {
          id: 4,
          name: "精靈金屬盔甲",
          src: "/src/assets/knight/equips/equip_BodyArmor.png",
          category: "armor bodyArmor",
          armor: 6,
          value: 0,
          safetyValue: 6,
          material: "奧里哈魯根",
          weight: 250,
          occupation: "[騎士][妖精]",
          feature: null,
        },
        {
          id: 5,
          name: "保護者斗篷",
          src: "/src/assets/knight/equips/equip_cloak.png",
          category: "armor cloak",
          armor: 3,
          value: 0,
          safetyValue: 4,
          material: "布",
          weight: 10,
          occupation: "[所有職業]",
          feature: null,
        },
        {
          id: 6,
          name: "瞬間移動控制戒指",
          src: "/src/assets/knight/equips/equip_left-ring.png",
          category: "jewelry left-ring",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "金",
          weight: 3,
          occupation: "[所有職業]",
          feature: "使用傳送術或傳送道具時，可以指定傳送到曾經記憶過的地點",
        },
        {
          id: 7,
          name: "身體腰帶",
          src: "/src/assets/knight/equips/equip_belt.png",
          category: "jewelry belt",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "皮",
          weight: 50,
          occupation: "[所有職業]",
          feature: "體力上限+50",
        },
        {
          id: 8,
          name: "精靈盾牌",
          src: "/src/assets/knight/equips/equip_shield.png",
          category: "armor shield",
          armor: 2,
          value: 0,
          safetyValue: 6,
          material: "銀",
          weight: 50,
          occupation: "[妖精][王族][騎士]",
          feature: null,
        },
        {
          id: 9,
          name: "力量手套",
          src: "/src/assets/knight/equips/equip_gloves.png",
          category: "armor gloves",
          armor: 0,
          value: 0,
          safetyValue: 4,
          material: "皮",
          weight: 18,
          occupation: "[所有職業]",
          feature: "力量 +2",
        },
        {
          id: 10,
          name: "形體控制戒指",
          src: "/src/assets/knight/equips/equip_right-ring.png",
          category: "jewelry right-ring",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "金",
          weight: 3,
          occupation: "[所有職業]",
          feature: "使用變身術或變身道具時，可以指定要變身的怪物",
        },
        {
          id: 11,
          name: "鋼鐵長靴",
          src: "/src/assets/knight/equips/equip_boots.png",
          category: "armor boots",
          armor: 3,
          value: 0,
          safetyValue: 4,
          material: "鐵",
          weight: 50,
          occupation: "[所有職業]",
          feature: null,
        },
      ],
    },
    elf: {
      basic: {
        lv: 1,
        exp: "0.00%",
        hp: 85,
        mp: 5,
        ac: 10,
        mr: 25,
        str: 11,
        dex: 19,
        con: 13,
        int: 12,
        wis: 12,
        cha: 9,
      },

      equips: [
        {
          id: 0,
          name: "尢米弓",
          src: `/src/assets/elf/equips/equip_weapon.png`,
          category: "weapon",

          attack: {
            small: 3,
            large: 3,
          },
          grip: "雙手武器",
          value: 0,
          safetyValue: 6,
          material: "木",
          weight: 40,
          occupation: "[妖精]",
          feature: "額外攻擊點數+2",
        },
        {
          id: 1,
          name: "艾爾穆的祝福",
          src: "/src/assets/elf/equips/equip_helmet.png",
          category: "armor helmet",

          armor: 2,
          value: 0,
          safetyValue: 6,
          material: "皮",
          weight: 13,
          occupation: "[妖精]",
          feature: "敏捷+1",
        },
        {
          id: 2,
          name: "妖魔戰士護身符",
          src: "/src/assets/elf/equips/equip_amulet.png",
          category: "jewelry amulet",

          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "寶石",
          weight: 5,
          occupation: "[所有職業]",
          feature: "體力上限+20",
        },
        {
          id: 3,
          name: "精靈T恤",
          src: "/src/assets/elf/equips/equip_shirt.png",
          category: "armor shirt",

          armor: 0,
          value: 0,
          safetyValue: 6,
          material: "布",
          weight: 5,
          occupation: "[妖精]",
          feature: null,
        },
        {
          id: 4,
          name: "精靈金屬盔甲",
          src: "/src/assets/elf/equips/equip_BodyArmor.png",
          category: "armor bodyArmor",

          armor: 6,
          value: 0,
          safetyValue: 6,
          material: "奧里哈魯根",
          weight: 250,
          occupation: "[騎士][妖精]",
          feature: null,
        },
        {
          id: 5,
          name: "精靈斗篷",
          src: "/src/assets/elf/equips/equip_cloak.png",
          category: "armor cloak",

          armor: 1,
          value: 0,
          safetyValue: 6,
          material: "布",
          weight: 10,
          occupation: "[所有職業]",
          feature: "妖精裝備時，體力回復量+1",
        },
        {
          id: 6,
          name: "瞬間移動控制戒指",
          src: "/src/assets/elf/equips/equip_left-ring.png",
          category: "jewelry left-ring",

          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "金",
          weight: 3,
          occupation: "[所有職業]",
          feature: "使用傳送術或傳送道具時，可以指定傳送到曾經記憶過的地點",
        },
        {
          id: 7,
          name: "身體腰帶",
          src: "/src/assets/elf/equips/equip_belt.png",
          category: "jewelry belt",

          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "皮",
          weight: 50,
          occupation: "[所有職業]",
          feature: "體力上限+50",
        },
        {
          id: 9,
          name: "腕甲",
          src: "/src/assets/elf/equips/equip_gloves.png",
          category: "armor gloves",

          armor: 0,
          value: 0,
          safetyValue: 4,
          material: "皮",
          weight: 10,
          occupation: "[騎士][妖精]",
          feature: "遠距離命中+2",
        },
        {
          id: 10,
          name: "形體控制戒指",
          src: "/src/assets/elf/equips/equip_right-ring.png",
          category: "jewelry right-ring",

          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "金",
          weight: 3,
          occupation: "[所有職業]",
          feature: "使用變身術或變身道具時，可以指定要變身的怪物",
        },
        {
          id: 11,
          name: "鋼鐵長靴",
          src: "/src/assets/elf/equips/equip_boots.png",
          category: "armor boots",

          armor: 3,
          value: 0,
          safetyValue: 4,
          material: "鐵",
          weight: 50,
          occupation: "[所有職業]",
          feature: null,
        },
      ],
    },
    magician: {
      basic: {
        lv: 1,
        exp: "0.00%",
        hp: 32,
        mp: 108,
        ac: 10,
        mr: 26,
        str: 8,
        dex: 7,
        con: 12,
        int: 19,
        wis: 18,
        cha: 12,
      },

      equips: [
        {
          id: 0,
          name: "瑪那魔杖",
          src: `/src/assets/magician/equips/equip_weapon.png`,
          category: "weapon",
          attack: {
            small: 7,
            large: 7,
          },
          grip: "單手武器",
          value: 0,
          safetyValue: 6,
          material: "木",
          weight: 15,
          occupation: "[法師]",
          feature: "魔攻+1",
        },
        {
          id: 1,
          name: "法師之帽",
          src: "/src/assets/magician/equips/equip_helmet.png",
          category: "armor helmet",
          armor: 2,
          value: 0,
          safetyValue: 4,
          material: "布",
          weight: 20,
          occupation: "[法師]",
          feature: "套裝效果(2/2): 魔力上限+50",
        },
        {
          id: 2,
          name: "妖魔戰士護身符",
          src: "/src/assets/magician/equips/equip_amulet.png",
          category: "jewelry amulet",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "寶石",
          weight: 5,
          occupation: "[所有職業]",
          feature: "體力上限+20",
        },
        {
          id: 3,
          name: "T恤",
          src: "/src/assets/magician/equips/equip_shirt.png",
          category: "armor shirt",
          armor: 0,
          value: 0,
          safetyValue: 4,
          material: "布",
          weight: 5,
          occupation: "[所有職業]",
          feature: null,
        },
        {
          id: 4,
          name: "法師長袍",
          src: "/src/assets/magician/equips/equip_BodyArmor.png",
          category: "armor bodyArmor",
          armor: 3,
          value: 0,
          safetyValue: 4,
          material: "布",
          weight: 60,
          occupation: "[法師]",
          feature: "套裝效果(2/2): 魔力上限+50",
        },
        {
          id: 5,
          name: "瑪那斗篷",
          src: "/src/assets/magician/equips/equip_cloak.png",
          category: "armor cloak",
          armor: 2,
          value: 0,
          safetyValue: 4,
          material: "布",
          weight: 10,
          occupation: "[法師]",
          feature: "魔力回復量+5",
        },
        {
          id: 6,
          name: "瞬間移動控制戒指",
          src: "/src/assets/magician/equips/equip_left-ring.png",
          category: "jewelry left-ring",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "金",
          weight: 3,
          occupation: "[所有職業]",
          feature: "使用傳送術或傳送道具時，可以指定傳送到曾經記憶過的地點",
        },
        {
          id: 7,
          name: "精神腰帶",
          src: "/src/assets/magician/equips/equip_belt.png",
          category: "jewelry belt",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "皮",
          weight: 50,
          occupation: "[所有職業]",
          feature: "魔力上限+50",
        },
        {
          id: 8,
          name: "魔法能量之書",
          src: "/src/assets/magician/equips/equip_shield.png",
          category: "armor shield",
          armor: 2,
          value: 0,
          safetyValue: 4,
          material: "紙",
          weight: 20,
          occupation: "[法師]",
          feature: "智力 +1",
        },
        {
          id: 9,
          name: "鋼鐵手套",
          src: "/src/assets/magician/equips/equip_gloves.png",
          category: "armor gloves",
          armor: 1,
          value: 0,
          safetyValue: 4,
          material: "鐵",
          weight: 40,
          occupation: "[所有職業]",
          feature: null,
        },
        {
          id: 10,
          name: "形體控制戒指",
          src: "/src/assets/magician/equips/equip_right-ring.png",
          category: "jewelry right-ring",
          armor: 0,
          value: 0,
          safetyValue: 0,
          material: "金",
          weight: 3,
          occupation: "[所有職業]",
          feature: "使用變身術或變身道具時，可以指定要變身的怪物",
        },
        {
          id: 11,
          name: "鋼鐵長靴",
          src: "/src/assets/magician/equips/equip_boots.png",
          category: "armor boots",
          armor: 3,
          value: 0,
          safetyValue: 4,
          material: "鐵",
          weight: 50,
          occupation: "[所有職業]",
          feature: null,
        },
      ],
    },
  });

  const roleBg = computed(
    () => `url(src/assets/${roleNow.value}/bg_${roleNow.value}.png)`
  );
  const roleData = computed(() => roles.value[roleNow.value]);
  return {
    roleNow,
    roleBg,
    roleData,
  };
});
